{{- if .Values.analytics.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  labels:
    app: analytics
spec:
  replicas: {{ .Values.analytics.replicas }}
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: {{ .Values.analytics.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          env:
            {{- include "common.env" . | nindent 12 }}
{{- end }}

