{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: {{ .Values.gateway.port }}
      targetPort: {{ .Values.gateway.port }}
{{- end }}
